public class WB_ServiceAppConstant{
    public static final String CLIENT_ID = 'CLIENT_ID'; 
    public static final String CLIENT_SECRET = 'CLIENT_SECRET'; 
    public static final String REFRESH_TOKEN = 'REFRESH_TOKEN';
    public static final String ACCESS_TOKEN = 'ACCESS_TOKEN';
    public static final String ENDPOINT_URL = 'ENDPOINT_URL';
    public static final String API_VERSION = 'API_VERSION';
    public static final String CODE = 'CODE';
    public static final String QUERY = 'QUERY';
    public static final String SOBJECT_NAME = 'SOBJECT_NAME';
    public static final String WB_SETTING = 'WB_ConsumerDetails';
    public static final String REDIRECT_URL = 'https://salesarena-dev-ed.my.site.com/workbenchhub/s/weblogin/oauthrequest';
    public static final Integer STATUS_OK = 200; 
    public static final String LISTVIEWNAME = 'LISTVIEWNAME';
    public static final String REQUESTBODY = 'REQUESTBODY';
}